### ISSUE TITLE
read value returns "empty" despite value is available

### ISSUE THREAD

**Issue by Kornelius777** [john30/ebusd#1566]
### Description

´´´
/usr/bin/ebusctl r -c solar ertraege 
empty

/usr/bin/ebusctl f
[...]
solar ertraege = 0.156;191;1;0;0;63;3
[...]
´´´

### Actual behavior

Value "solar --> ertraege" exists 
However, if I explicitly ask for it, the return reads "empty"

### Expected behavior

return correct value

### ebusd version

25.1

### ebusd arguments

--pidfile /var/run/ebusd.pid --readonly --configlang=de --configpath=/etc/ebusd --device=/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9WFNXT5-if00-port0 --port=8888

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

other

### Related integration

other

### Logs

2025-07-26 11:05:20.594 [update notice] received update-read solar ertraege QQ=71: 0.000;48;2;1;0;63;3

**Comment by john30** [comment]
please share the message definition

**Comment by Kornelius777** [comment]
Sorry, no clue what you want.
Which message?

**Comment by Kornelius777** [comment]
Would you like my csv file?
Here it comes:
```
# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment
*r,solar,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
w,,ertraege,,,,5018,,leistung,,D2B,,,Solarleistung,ertraglow,,UCH,,,ErtragTagLow,ertraghigh,,UCH,,,ErtragTagHigh,ertragsummelow,,UCH,,,SummeErtragLow,summertraghigh,,UCH,,,SummeErtragHigh,ertragsumme,,UCH,,,SummeErtragM,,,,,,
w,,temp,,,,5017,,pumpe,,UCH,0xbc=off;0xbd=on,,SolarPumpe,,,IGN:1,,,,kollektortemp,,temp,,,Kollektortemperatur,wwsolartemp,,temp,,,WW Solartemperatur,,,,,,,,,,,,,,,,,,
r,,regler,,,50,5014,,status,,HEX,,,StatusSolar,,,IGN:1,,,,mischersolltemp,,temp2,,,MischerSolltemperatur,raumtemp,,temp1,,,Raumtemperatur,wwsolltemp,,temp1,,,SollWarmwasser,,,,,,,,,,,,
```

**Comment by Kornelius777** [comment]
By the way: 
I went back to 24.1, and everything works fine, there

**Comment by john30** [comment]
yes, i meant the csv. and what is the target address? or does the file name carry a target address?

**Comment by Kornelius777** [comment]
file name is 50.csv

**Comment by Kornelius777** [comment]
As mentioned above: 
I went back to 24.1, and everything works fine, there

**Comment by john30** [comment]
fixed a minute ago @Kornelius777.
anyway, the message definition is rather weird.
can you tell me what the parts ErtragTagLow and ErtragTagHigh actually mean? is it valid to combine the two into a single value, e.g. ErtragTag = ErtragTagLow + ErtragTagHigh*256 or similar?
same for the SummeErtrag, but that might be a bit trickier due to 3 bytes, but when the factor is indeed 256, then this could as well be simplified

**Comment by Herr-Frodo** [comment]
The problem still exist here too:
Domoticz plugin works fine with any version up to 24.1 but gives the above error with the latest 25.x release.
('official' Weishaupt/Komschröder .csv - Weishaupt WTC/EM)

**Comment by john30** [comment]
> The problem still exist here too: Domoticz plugin works fine with any version up to 24.1 but gives the above error with the latest 25.x release. ('official' Weishaupt/Komschröder .csv - Weishaupt WTC/EM)

did you try with a build from the sources or with the release only?
