### ISSUE TITLE
Arbitration lost on C6 shield after 2025-01-20

### ISSUE THREAD

**Issue by maleadt** [john30/ebusd#1622]
### Description

Opening https://github.com/john30/ebusd/discussions/1516 as an issue, after I verified this still occurs on the latest firmware (2025-11-16). On my eBUS Adapter Shield C6, connected to a RPi 5, I cannot get any firmware later than 2025-01-20 to work.

### Actual behavior

Arbitration failed reported in ebusd logs.

### Expected behavior

Everything to work as it does on firmware 2025-01-20.

### ebusd version

25.1

### ebusd arguments

--device=/dev/ttyAMA0 --group-add keep-groups john30/ebusd --device=ens:/dev/ttyAMA0 --log=all:notice --mqtthost=myhost --mqttport=1883 --mqttjson --mqttint=/etc/ebusd/mqtt-hassio.cfg --latency=50

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

arm64

### Dockerized

latest

### Hardware interface

Adapter Shield v5/C6 via Raspberry GPIO

### Logs

```
2025-11-18 15:01:11.408 [device notice] transport opened
2025-11-18 15:01:11.436 [main notice] ebusd 25.1.25.1 started with broadcast scan on device: /dev/ttyAMA0, serial high speed, enhanced
2025-11-18 15:01:11.698 [bus notice] bus started with own address 31/36
2025-11-18 15:01:11.698 [bus notice] signal acquired
2025-11-18 15:01:11.699 [mqtt notice] connection established
2025-11-18 15:01:19.385 [bus notice] new master 10, master count 2
2025-11-18 15:01:19.454 [bus notice] new master 03, master count 3
2025-11-18 15:01:19.454 [update notice] received unknown MS cmd: 1008b5110101 / 09282a2007282b0000ff
2025-11-18 15:01:19.750 [update notice] received unknown MS cmd: 1052b5230103 / 0f00800080008000804d013c01c87d00
2025-11-18 15:01:20.020 [update notice] received unknown MS cmd: 1008b51009000000ffffff010000 / 0101
2025-11-18 15:01:20.283 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-11-18 15:01:20.532 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-11-18 15:01:21.699 [main notice] starting initial broadcast scan
2025-11-18 15:01:22.240 [bus error] send to fe: ERR: arbitration lost, retry
2025-11-18 15:01:22.807 [bus error] send to fe: ERR: arbitration lost, retry
2025-11-18 15:01:23.373 [bus error] send to fe: ERR: arbitration lost
2025-11-18 15:01:23.373 [main error] initial scan failed: ERR: arbitration lost
```

**Comment by larsimmisch** [comment]
Thanks! The tip to downgrade the firmware to 2025-01-20 helped me a lot. I have a new installation here (details below) and before the downgrade, I mostly got `[main error] initial scan failed: ERR: arbitration lost` and `ebusctl info` showed no descriptions for any devices.

My hardware interface is also an Adapter Shield v5/C6 via Raspberry GPIO.

After downgrading the firmware, I get this, which looks a lot better:

```
version: ebusd 25.1.25.1-16-g255f1768
update check: revision 25.1 available, device firmware v5-c6 1[5b17] available
device: /dev/ttyAMA0, serial high speed, enhanced, firmware 1.1[5114].1[5114]
signal: acquired
symbol rate: 22
max symbol rate: 166
min arbitration micros: 5
max arbitration micros: 8
min symbol latency: 4
max symbol latency: 4
scan: finished
reconnects: 0
masters: 6
messages: 5
conditional: 0
poll: 0
update: 0
address 03: master #11
address 04: slave #25, scanned "MF=Vaillant;ID=NETX3;SW=0128;HW=0404"
address 08: slave #11, scanned "MF=Vaillant;ID=HMUX0;SW=0405;HW=0504"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=CTLV3;SW=0808;HW=8004"
address 31: master #8, ebusd
address 36: slave #8, ebusd
address 71: master #9
address 76: slave #9, scanned "MF=Vaillant;ID=VWZIO;SW=0405;HW=0504"
address f1: master #10
address f6: slave #10, scanned "MF=Vaillant;ID=NETX3;SW=0128;HW=0404"
address ff: master #25
``` 

So to me it looks as if the newest firmware of the v5/C6 via Raspberry Pi GPIO is indeed broken.

## Installation details:

- Außeneinheit aroTHERM plus VWL 75/6A S2
- Inneneinheit: uniTOWER plus VIH QW190 (190l Warmwasserspeicher, 9kW Heizstab)
- Internetgateway VR 940
- Regler sensoCOMFORT

**Comment by john30** [comment]
can't reproduce this on a RPI4B. I don't use any special latency setting though.
could someone please post ebusd logging from the start (with the problematic message included) with using "--lograwdata=bytes"?

EDIT: same on a RPI5

**Comment by larsimmisch** [comment]
These are the logfiles I could get with `sudo ebusd --scanconfig -d ens:/dev/ttyAMA0 --lograwdata=bytes --lograwdatafile=ebusd.txt --loglevel=info --pidfile=/var/run/ebusd.pid --logfile=/var/log/ebusd.log`

I'm running ebusd on a Raspberry Pi 3, the firmware is version 2025-01-20

Should I maybe try the same with the latest firmware installed?

[ebusd.log](https://github.com/user-attachments/files/23853433/ebusd.log)
[ebusd.txt](https://github.com/user-attachments/files/23853434/ebusd.txt)

**Comment by john30** [comment]
> Should I maybe try the same with the latest firmware installed?

yes of course
and don't use "--lograwdatafile" to have all logging in a single file

**Comment by larsimmisch** [comment]
Attached is the output of:
`sudo ebusd -f --scanconfig -d ens:/dev/ttyAMA0  --loglevel=info --pidfile=/var/run/ebusd.pid --lograwdata=bytes > ebusd.log`, all in a single file.

This is with the 2025-11-30 firmware, hope it helps debugging.

[ebusd.log](https://github.com/user-attachments/files/23880005/ebusd.log)

**Comment by john30** [comment]
thanks for the log.
I was able to reproduce it on a RPI3 and already found the cause (a silent drop of the RX pin pull-up with [commit a1ba653](https://github.com/espressif/esp-idf/commit/a1ba653952606d9c122f5eb01ad513e6c031dc7c#diff-82bd09b087ffa44fe79a57244cc2c94a4ff1c0d25a62af4652bd2820487fff9a) in January 2025). That one I've overseen obviously.
It could probably be circumvented by using the RPI GPIO pull-up for the TX line, but I'll adjust it in the next release anyway.

**Comment by larsimmisch** [comment]
Thanks!

**Comment by john30** [comment]
solved in https://github.com/john30/ebusd-esp32/commit/1f31fd9514b93e8f03b90b974c067cfc0512fb1a

**Comment by maleadt** [comment]
This is not fixed for me on 2025-12-07:

```
[14:22:51]easi> info
[14:22:51]Chip: ESP32-C6, rev 1
[14:22:51]PCB: 2.36.0
[14:22:51]Build: 20251207
[14:22:51]Partition: 0
[14:22:51]HW ID: e4b32394a800
[14:22:51]Default hostname: ebus-94a800
[14:22:51]RAM: 345908
[14:22:51]Uptime: 27
```

```
2025-12-09 13:14:22.934 [device notice] transport opened
2025-12-09 13:14:22.958 [main notice] ebusd 25.1.25.1 started with broadcast scan on device: /dev/ttyAMA0, serial high speed, enhanced
2025-12-09 13:14:23.548 [bus notice] bus started with own address 31/36
2025-12-09 13:14:23.548 [bus notice] signal acquired
2025-12-09 13:14:23.548 [bus notice] new master 10, master count 2
2025-12-09 13:14:23.548 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-12-09 13:14:23.548 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-12-09 13:14:23.548 [mqtt notice] connection established
2025-12-09 13:14:32.316 [bus notice] new master 03, master count 3
2025-12-09 13:14:32.316 [update notice] received unknown MS cmd: 1008b5110101 / 092f31c00e2e340000ff
2025-12-09 13:14:32.612 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008088016a01c87d00
2025-12-09 13:14:32.884 [update notice] received unknown MS cmd: 1008b51009000000ffffff010000 / 0101
2025-12-09 13:14:33.146 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-12-09 13:14:33.396 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-12-09 13:14:33.548 [main notice] starting initial broadcast scan
2025-12-09 13:14:34.100 [bus error] send to fe: ERR: arbitration lost, retry
2025-12-09 13:14:34.665 [bus error] send to fe: ERR: arbitration lost, retry
2025-12-09 13:14:35.233 [bus error] send to fe: ERR: arbitration lost
2025-12-09 13:14:35.233 [main error] initial scan failed: ERR: arbitration lost
2025-12-09 13:14:42.397 [update notice] received unknown MS cmd: 1008b5110101 / 092f31c00e2e340000ff
2025-12-09 13:14:42.693 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008088016b01c87d00
2025-12-09 13:14:42.963 [update notice] received unknown MS cmd: 1008b51009000000ffffff010000 / 0101
2025-12-09 13:14:43.226 [update notice] received unknown MS cmd: 1008b5110102 / 06013c96468274
2025-12-09 13:14:43.506 [update notice] received unknown MS cmd: 1008b5040100 / 0a0333161409120225c00e
2025-12-09 13:14:43.744 [update notice] received unknown BC cmd: 10feb516080032161409120225
2025-12-09 13:14:44.005 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-12-09 13:14:44.274 [update notice] received unknown MS cmd: 1008b5110100 / 087e010a001f000000
2025-12-09 13:14:44.522 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-12-09 13:14:44.739 [update notice] received unknown BC cmd: 10feb5160301c00e
2025-12-09 13:14:45.233 [main notice] starting initial broadcast scan
2025-12-09 13:14:45.791 [bus error] send to fe: ERR: arbitration lost, retry
2025-12-09 13:14:46.359 [bus error] send to fe: ERR: arbitration lost, retry
2025-12-09 13:14:46.927 [bus error] send to fe: ERR: arbitration lost
2025-12-09 13:14:46.927 [main error] initial scan failed: ERR: arbitration lost
2025-12-09 13:16:38.132 [main notice] starting initial broadcast scan
2025-12-09 13:16:38.681 [bus error] send to fe: ERR: arbitration lost, retry
2025-12-09 13:16:39.248 [bus error] send to fe: ERR: arbitration lost, retry
2025-12-09 13:16:39.815 [bus error] send to fe: ERR: arbitration lost
2025-12-09 13:16:39.815 [main error] initial scan failed: ERR: arbitration lost
2025-12-09 13:16:39.999 [main notice] update check: OK
2025-12-09 13:16:41.091 [update notice] received unknown MS cmd: 1008b5110101 / 092f31c00e2e340000ff
2025-12-09 13:16:41.385 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008088016a01c87d00
2025-12-09 13:16:41.656 [update notice] received unknown MS cmd: 1008b51009000000ffffff010000 / 0101
2025-12-09 13:16:41.918 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-12-09 13:16:42.011 [bus notice] max. symbols per second: 101
2025-12-09 13:16:42.168 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-12-09 13:16:49.999 [main notice] starting initial broadcast scan
2025-12-09 13:16:50.545 [bus error] send to fe: ERR: arbitration lost, retry
...
```

Verbose log: [ebusd.log](https://github.com/user-attachments/files/24055963/ebusd.log)

Reverting makes things work again:

```
2025-12-09 13:24:07.847 [device notice] transport opened
2025-12-09 13:24:07.849 [main notice] ebusd 25.1.25.1 started with broadcast scan on device: /dev/ttyAMA0, serial high speed, enhanced
2025-12-09 13:24:08.076 [bus notice] bus started with own address 31/36
2025-12-09 13:24:08.076 [device notice] reset, supports info
2025-12-09 13:24:08.076 [bus notice] signal acquired
2025-12-09 13:24:08.077 [mqtt notice] connection established
2025-12-09 13:24:08.078 [device notice] extra info: firmware 1.1[5114].1[5114], jumpers 0x03
2025-12-09 13:24:14.045 [bus notice] new master 10, master count 2
2025-12-09 13:24:14.116 [bus notice] new master 03, master count 3
2025-12-09 13:24:14.116 [update notice] received unknown MS cmd: 1008b5110101 / 092f31c00e2d330000ff
2025-12-09 13:24:14.412 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008086016901c87d00
2025-12-09 13:24:14.685 [update notice] received unknown MS cmd: 1008b51009000000ffffff010000 / 0101
2025-12-09 13:24:14.945 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-12-09 13:24:15.036 [bus notice] max. symbols per second: 103
2025-12-09 13:24:15.193 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-12-09 13:24:18.077 [main notice] starting initial broadcast scan
2025-12-09 13:24:18.189 [update notice] sent write Broadcast Queryexistence QQ=31:
2025-12-09 13:24:24.177 [update notice] received unknown MS cmd: 1008b5110101 / 092f31c00e2d330000ff
2025-12-09 13:24:24.474 [update notice] received unknown MS cmd: 1052b5230103 / 0f008000800080008086016901c87d00
2025-12-09 13:24:24.745 [update notice] received unknown MS cmd: 1008b51009000000ffffff010000 / 0101
2025-12-09 13:24:25.050 [update notice] received unknown MS cmd: 1052b523080100ff0000ffff00 / 0101
2025-12-09 13:24:25.298 [update notice] received unknown MS cmd: 1052b5230402010000 / 02019c
2025-12-09 13:24:28.366 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
2025-12-09 13:24:28.366 [update notice] store 08 ident: done
2025-12-09 13:24:28.366 [update notice] sent scan-read scan.08  QQ=31: Vaillant;BAI00;0104;7803
2025-12-09 13:24:28.366 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
...
```

**Comment by john30** [comment]
> This is not fixed for me on 2025-12-07:

I can't reproduce this with the same setup, i.e. RPI5 running Bookworm with v5-C6 adapter.
did you follow the [RPI5 specific setup](https://adapter.ebusd.eu/v5-c6/raspberrypi.en)?

**Comment by larsimmisch** [comment]
On my Raspberry 3, I also get `[bus error] send to fe: ERR: arbitration lost, retry` again after the update to 2025-12-07. A logfile with raw bytes is attached.

[ebusd.log](https://github.com/user-attachments/files/24151798/ebusd.log)

**Comment by ghhausi** [comment]
**meTOO**
I have the new C6 Adapter with FW 20251214 on an Raspberry PI 5 with OS based on Debian Trixie
gert@meetering:~ $ uname -a
Linux meetering 6.12.47+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.47-1+rpt1 (2025-09-16) aarch64 GNU/Linux

And no I **did not try an almost one year old firmware** (2025-01-20)

Observation (compared to any old V5 Adapter on a Pi 3):
ebusctl I    does not show the firmware

<img width="421" height="367" alt="Image" src="https://github.com/user-attachments/assets/c7843f89-66e4-4893-b3cf-2818972411f6" />

The log looks similar to the already published comments. After the initial sequence I get "[bus error] send to fe: ERR: arbitration lost, retry

<img width="881" height="900" alt="Image" src="https://github.com/user-attachments/assets/07a75ec0-8a78-41ec-913f-33594a3e7690" />

Please provide a solution.
Thank you!

**Comment by john30** [comment]
@maleadt I've started to migrate to IDF 5.5 and using the testing firmware I was still not able to reproduce it with the same versions on my RPi5. Could you please give it a try by installing the testingc6.bin pointing your browser to a URL like this "`http://<adapterip>?file=testingc6.bin`" (with "`<adapterip>`" replaced by your actual adapter IP) and then going to "Update Firmware" and clicking "Update to specific file: testingc6.bin"?

**Comment by jstoki** [comment]
Hi, I am the author of the previous issue #1516 . I am using Shield C6 with RPi3 and unfortunately uploading firmware version 2025-12-14 did not help.
Can I also test the proposed update or it is specific for RPi5?

**Comment by john30** [comment]
> Hi, I am the author of the previous issue [#1516](https://github.com/john30/ebusd/discussions/1516) . I am using Shield C6 with RPi3 and unfortunately uploading firmware version 2025-12-14 did not help. Can I also test the proposed update or it is specific for RPi5?

yes please, as the cause seems to be more than just the missing pull-up.
however noone answered whether the RPi setup instructions were followed, so this might be it as well (because I did follow them of course)

**Comment by ghhausi** [comment]
Good morning,
with "RPi setup instructions" you mean the section [here](https://adapter.ebusd.eu/v5-c6/raspberrypi.en#rpi5) 
As I brought a new C6 adapter for my PRi 5 I did nothing with GPIO 27, because it's not connected to the adapter. The rest of the configuration is the following:
- I am using a local ebusd-config 

<img width="1028" height="161" alt="Image" src="https://github.com/user-attachments/assets/37f6786e-8838-4709-be26-450cdbedc62f" />

- I am running latest PRi-OS based on Debian Trixie

<img width="879" height="547" alt="Image" src="https://github.com/user-attachments/assets/79a2703e-07ec-40f6-9e3e-29d7a7a82a2c" />


As you can see - it runs with the very old firmware (January 2025)

Now: I am willing to test - but you have to give me more details on "_testingc6.bin pointing your browser to a URL like this "http://<adapterip>?file=testingc6.bin" (with "" replace by your actual adapter IP)_"
The C6 Adapter is attached to an RPi 5. I do FW-Updates using the method mentioned on the ebusd-web page:
- take the adapter out of the raspi
- use USB/JTAG serial debug unit (COM...) + CONNECT 
- update

Now I don't know how to deal with "testingc6.bin".

And please bear in mind: My RPi sits in a rack and does more than just monitor the ebus --> that means: Flashing a test-FW means flash the old (working) FW as well and put it back into the rack - because I need the ebus-data.

**Comment by john30** [comment]
I'm referring to the PL011 switch which is needed for RPi as explained [here](https://adapter.ebusd.eu/v5-c6/raspberrypi.en#configuration-with-raspberry-pi-os)
so you don't have any network configured on the adapter? you could just use the temporary access point and leave the adapter on the RPi if you can reach the button.
otherwise, you can use [this URL](https://adapter.ebusd.eu/v5/firmware_version?file=testing) for the webserial browser flashing

**Comment by ghhausi** [comment]
Hi John,
sorry update via "https://adapter.ebusd.eu/v5/firmware_version?file=testing" does not work:
When I connect for "webserial browser flashing" I get

<img width="414" height="215" alt="Image" src="https://github.com/user-attachments/assets/b98460f9-4626-47d6-930a-f6a6aea0bf0e" />

**and then:**


<img width="482" height="323" alt="Image" src="https://github.com/user-attachments/assets/5084a19e-ca1c-4bad-a598-ab31449e960d" />


Please check and let me know....

best regards
Gerhard

**Comment by john30** [comment]
ah, wrong file name. changed it, so please reload and it should work now

**Comment by jstoki** [comment]
Hi
What is the correct file name?
I have been trying to do this via Wi-Fi, but after entering the URL (inc adapter IP):
http://192.168.20.41?file=testingc6.bin
http://192.168.20.41?file=testing.bin
http://192.168.20.41?file=testing
I am always redirected to the adapter's main page:
http://192.168.20.41/?file=testing#/status
where there is no information about this update.

<img width="683" height="612" alt="Image" src="https://github.com/user-attachments/assets/536f242f-d819-42ba-8a9d-756bbae72730" />
In a moment, I'll try with the URL via webserial.

**Comment by john30** [comment]
as I wrote before: https://github.com/john30/ebusd/issues/1622#issuecomment-3707067135, i.e. you still need to issue the update on the webpage

**Comment by jstoki** [comment]
Hi

Thank you very much John for your support. On my **Rpi3 Bookworm + Shield C6**, after the update, the “arbitration” errors disappeared and the system immediately recognized all devices.

**uname -a**
```
Linux status 6.12.47+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.47-1+rpt1~bookworm (2025-09-16) aarch64 GNU/Linux
```
**dmesg|grep ttyAMA0**
```
[    2.613381] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 99, base_baud = 0) is a PL011 rev2

```

**ebusctl i**
```
version: ebusd 25.1.25.1
update check: OK, device firmware v5-c6 1[5c1f] available, vaillant/26.vr_71.csv: different version available
device: /dev/ttyAMA0, serial high speed, enhanced, firmware 1.1[6103].1[6103]
signal: acquired
symbol rate: 79
max symbol rate: 124
min arbitration micros: 2
max arbitration micros: 121
min symbol latency: 4
max symbol latency: 6
scan: finished
reconnects: 0
masters: 4
messages: 711
conditional: 0
poll: 0
update: 16
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0609;HW=5502", loaded "vaillant/bai.0010011701.inc" ([id_hw=5502]), "vaillant/08.bai.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=70000;SW=0419;HW=4603", loaded "vaillant/15.700.csv"
address 26: slave, scanned "MF=Vaillant;ID=VR_71;SW=0104;HW=0503", loaded "vaillant/26.vr_71.csv"
address 30: master #3
address 31: master #8, ebusd
address 35: slave #3, scanned "MF=Vaillant;ID=VR_91;SW=0411;HW=4803"
address 36: slave #8, ebusd

```

**Comment by john30** [comment]
thanks for checking. hm, weird anyway since I was not able to reproduce with my RPi3, neither with a C6 nor with a C3.

**Comment by jstoki** [comment]
Could it be a coincidence of the system/Shield/firmware version?
It probably isn't a very common problem, since only a few people have raised the issue.
In any case, it started working :)

**Comment by ghhausi** [comment]
Hi everybody - reporting **success with "testingc6.bin**" from my side as well!

I does scanconfig with no error and reporting the firmware version correctly:

<img width="901" height="490" alt="Image" src="https://github.com/user-attachments/assets/43996791-5c83-41b8-a885-b78d0b72b16d" />

ebusd.log **does not show** any "**arbitration lost**".....
I keep the current/testing FW running for the moment - **please let us know when to use an "official" one**.

<img width="941" height="545" alt="Image" src="https://github.com/user-attachments/assets/7982a060-7468-4ee9-96e7-e4ba256a7ea8" />

John: Thanks for your help!

**Comment by john30** [comment]
thanks for checking. I was looking at the changes of esp-idf/components/esp_driver_uart from v5.3 to v5.5 again, but there are so many potential candidates, that it is really hard to tell, which one might be the reason.
anyway, it seems to be ok now - fingers crossed that espressif will not rework the driver so heavily again...

**Comment by mfore1** [comment]
I have a similar issue, probably the same:

2026-02-24 22:49:44.548 [update notice] received update-read Broadcast Datetime QQ=10: 10.000;22:49:17;24.02.2026
2026-02-24 22:49:44.758 [update notice] received unknown MS cmd: 011506210400ba0046 / 0a3a800308640000000080
2026-02-24 22:49:45.024 [main notice] starting initial broadcast scan
2026-02-24 22:49:45.625 [bus error] send to fe: ERR: arbitration lost, retry
2026-02-24 22:49:45.821 [update notice] received unknown MS cmd: 011506210400810046 / 0a01000d02f40100000080
2026-02-24 22:49:46.313 [bus error] send to fe: ERR: arbitration lost, retry
2026-02-24 22:49:46.930 [update notice] received unknown MS cmd: 011506210402c80040 / 0a4841042a9f0500005905
2026-02-24 22:49:47.000 [bus error] send to fe: ERR: arbitration lost
2026-02-24 22:49:47.000 [main error] initial scan failed: ERR: arbitration lost
2026-02-24 22:49:48.040 [update notice] received unknown MS cmd: 011506210402c90040 / 0a49c10000060000000100
2026-02-24 22:49:49.102 [update notice] received unknown MS cmd: 011506210402b30048 / 0a33810000ff0000000000
2026-02-24 22:49:49.296 [update notice] received unknown BC cmd: 10fe100a0c110064000000000000001400

I tried different firmware versison on the C6 adapter with RPI 4B
Error above is from Firmware 20260222

$ ebusctl i
version: ebusd 26.1.26.1
update check: OK
device: /dev/ttyAMA0, serial high speed, enhanced
signal: acquired
symbol rate: 44
max symbol rate: 84
reconnects: 0
masters: 5
messages: 17
conditional: 0
poll: 0
update: 10
address 01: master #6
address 03: master #11
address 10: master #2
address 13: master #12
address 15: slave #2
address 31: master #8, ebusd
address 36: slave #8, ebusd

What might I be doing wrong?

Thanks!

**Comment by ghhausi** [comment]
John is right: It is **not a ebusd problem** - but it's a  problem with the firmware ..... and I don't see a solution.
Is OK as long as I get my things done with the [very] old firmware.

**Comment by mfore1** [comment]
I tried "Version 2026-02-22" and Version "2025-12-31". Both did not work for me. Which one should I try to use?

**Comment by mfore1** [comment]
Answered by myself and trial and error.
Last (or first when downgrading) working version seems to be 20250120

Now I get: 
$ ebusctl i
version: ebusd 26.1.26.1
update check: OK
device: /dev/ttyAMA0, serial high speed, enhanced
signal: acquired
symbol rate: 94
max symbol rate: 117
min arbitration micros: 1
max arbitration micros: 7
min symbol latency: 4
max symbol latency: 4
scan: finished, some messages pending
reconnects: 0
masters: 5
messages: 32
conditional: 0
poll: 0
update: 10
address 01: master #6
address 03: master #11
address 06: slave #6, scanned "MF=TEM;ID=21692;SW=0153;HW=0000"
address 08: slave #11, scanned "MF=TEM;ID=WE_1 ;SW=3632;HW=3030"
address 10: master #2
address 13: master #12
address 15: slave #2, scanned "MF=TEM;ID=19348;SW=0363;HW=0102"
address 18: slave #12, scanned "MF=TEM;ID=WE_2 ;SW=3632;HW=3030"
address 31: master #8, ebusd
address 36: slave #8, ebusd

**Comment by john30** [comment]
I think I might have just found the root cause while checking [recent changes of the uart driver](https://github.com/espressif/esp-idf/commit/8974851c8a5160e567f4ba615686728c09b47dd9), see my comments [here](https://github.com/espressif/esp-idf/issues/13116#issuecomment-4072849099).
I'm going to prepare a new testing version soon that circumvents the weird api behaviour and thus should remove the arbitrary time dependency there. would be great if someone could test it then as I'm not able to reproduce it

**Comment by ghhausi** [comment]
OK - let me know when it is ready to test - I- want to give it a try.

**Comment by john30** [comment]
great, thanks. I've tried it with my Raspi 4 now, works for me just as before. Raspi 5 I can only test on the weekend.
If you want to give it a try, then point your browser to `http://adapterip/?file=testingc6.bin` with your adapter IP, then click on "Update Firmware" on the webpage and then on "Update to specific file...".

**Comment by ghhausi** [comment]
Sorry I cannot make it before Monday (I a not at home right now).....maybe Sunday late afternoon

**Comment by john30** [comment]
just tested it on Raspi 5 and also behaves as expected (even though that doesn't say much as it always worked for me in the past as well)

**Comment by ghhausi** [comment]
Sorry I was not able to test "testingc6.bin" --> The Adapter is in a PI5 which sits in a Rack (the Adapter has no WIFi, because it is plugged into a PI)  ... so "http://adapterip/?file=testingc6.bin" did not work for me.

I did a quick test on "2026-03-17" which does not work ("arbitration error")
So I ab back to 2025-01-20 and stay there until other people e.g. "mfore1" reports success on a newer one

**Comment by Luric76** [comment]
Hi john30,

I’ve tested the testingc6.bin (Build 20260321) on my setup and wanted to give you some feedback.

My Setup:
Hardware: EBUS Adapter Shield 6 rev 2 (powered via USB-C).
Host: Raspberry Pi 3 Model B Rev 1.2 (Docker).
Bus: High activity with 5 Masters.

Even with the new firmware, I am still getting [bus error] send to fe: ERR: arbitration lost during the initial broadcast scan. The scan fails every time.

There is no noticeable difference between the previous build (latest) and testingc6.bin regarding the ability to send or scan.

The adapter does receive data (I see unknown MS cmd in the logs), but it seems incapable of successfully sending a broadcast without being "kicked" off the bus by other masters.

Could the timing issues be specific to the older GPIO architecture of the Pi 3B when dealing with 5 other masters? Is there any specific latency or delay parameter you would recommend for this older hardware?

Thanks for looking into this!

Michael

[ebusd_log.txt](https://github.com/user-attachments/files/26196569/ebusd_log.txt)
[info_log.txt](https://github.com/user-attachments/files/26196570/info_log.txt)

**Comment by john30** [comment]
I've done a whole lot of investigation on this topic now (more than 2 full days of the weekend in total) and last week I finally got my raspi 5 to reproduce the issue (funny since there was basically no change to the setup, but anyway...).
at some point I suspected the voltage level to potentially be an issue and today I've checked it with my oscilloscope and indeed this seems to be the root cause as the voltage level (in case of the issue) just does not go down low enough in order to detect a logic low level when ebusd wants to send something to the device (it pulls the level down to around 2V which is way too high compared to the expected <0.8V). as a consequence, the device wouldn't see any data coming from the host at all and as such wouldn't start arbitration or answer to queries from ebusd in any way.
the root cause for this is that the RX line is left in an unclean state by the UART driver of ESP-IDF due to [commit a1ba65](https://github.com/espressif/esp-idf/commit/a1ba653952606d9c122f5eb01ad513e6c031dc7c#diff-82bd09b087ffa44fe79a57244cc2c94a4ff1c0d25a62af4652bd2820487fff9aL762) where `gpio_set_direction(rx_io_num, GPIO_MODE_INPUT)` was replaced with `gpio_ll_input_enable(...)` which leaves the output part of the pin in the state it was before, which results in this really weird voltage level on the pin that prevents detecting uart input.

bottom line: this weird situation can be get rid off (at least on my setup) by issuing a simple "io -iu 4" on the repl. this way the output is detached from the pin and the voltage level goes back to normal.
if anyone wants to try the updated firmware: use `http://youadapterip/?file=testingc6.bin` and "update firmware" plus "update to specific file..." to update to that one

edit: filed a [new issue on esp-idf](https://github.com/espressif/esp-idf/issues/18404)

**Comment by ghhausi** [comment]
John: Thanks for work - I will give it a try in the next days. 
(Will wait until these fixes are reflected in an "official" FW from the Web-Site.
